### ISSUE TITLE
Stop discovering added devices

### ISSUE THREAD

**Issue by t3lmoazevedo** [luuuis/hass_wibeee#28]
Is it possible to stop discovering the same devices that are added already?
Thanks

![image](https://user-images.githubusercontent.com/41584793/148455731-a6fbba8d-04f8-4fca-bbf1-4e86fd1a18ba.png)

**Comment by luuuis** [comment]
Hi @t3lmoazevedo, can you include a bit more information about what's happening?
1. Do you still have the `platform: wibeee` entries in `configuration.yaml`? (you can remove these after they've been imported into config)
2. When do the new devices appear, what HA version, etc?

**Comment by t3lmoazevedo** [comment]
Home Assistant core-2021.12.8
OK, removing the entries from configuration.yaml resolved the issue. Thanks
