### ISSUE TITLE
Energy

### ISSUE THREAD

**Issue by macoca28021** [luuuis/hass_wibeee#35]
Good morning again, sorry to bother you again. Let's see if you can help me again. As you can see in the attachment, the consumption graphs are not visible. As you can see, the entity gives values ​​that are not normal. Greetings and thanks again.

![Screenshot_63](https://user-images.githubusercontent.com/82387245/153137024-3cedd497-d4db-40c3-81d9-04000bed5ad2.png)
![Screenshot_64](https://user-images.githubusercontent.com/82387245/153137599-3e355030-4d19-4814-aa28-a9890de6a9e8.png)
![Screenshot_66](https://user-images.githubusercontent.com/82387245/153140786-3f6339cd-b66b-471e-906c-938c62b3c671.png)

**Comment by homerj31** [comment]
parece que el problema esta aquí, o eso creo

![image](https://user-images.githubusercontent.com/40171213/153179903-304fb4b1-ed96-4f0c-9d7e-59c09b1e3975.png)

**Comment by luuuis** [comment]
@macoca28021 are you using the right sensor/clamp?  The L4 sensor is the one providing the total consumption as far as I'm aware. 

Please post the screenshot from the Wibeee UI showing the reported values for each clamp (accessible from the device IP using a browser).

**Comment by macoca28021** [comment]
> @macoca28021 ¿está usando el sensor/abrazadera correctos? El sensor L4 es el que proporciona el consumo total que yo sepa.
> 
> Publique la captura de pantalla de la interfaz de usuario de Wibeee que muestra los valores informados para cada abrazadera (accesible desde la IP del dispositivo mediante un navegador).

L4, as I understand it, is the total consumption but with three-phase current and I don't have that. Anyway, I change it to L4 and I'll tell you but that's not going to be.

**Comment by luuuis** [comment]
Instead of trying different sensors blindly why don't you look at what values you have for L1, L2 and L3 right now? You can check this in the Entities screen in HA or in the History tab (search for the Active Energy sensors).

The graph should show an ever- increasing value.

**Comment by homerj31** [comment]
![image](https://user-images.githubusercontent.com/40171213/153213566-4f20c2ca-502a-477d-a151-5a7e48230930.png)

quitando el float si parece volver a contar bien

![image](https://user-images.githubusercontent.com/40171213/153213700-e4eba0b0-795f-4300-ae7e-7ee79dacb8fe.png)

**Comment by macoca28021** [comment]
![image](https://user-images.githubusercontent.com/82387245/153220075-f27da082-37e4-455d-bf60-aeff5b179515.png)
Si, los contadores están locos, como se soluciona esto???
dices de quitar el float, pero no se que es

**Comment by homerj31** [comment]
en la configuracion esta

https://github.com/luuuis/hass_wibeee/blob/main/SENSOR_EXAMPLES.md

se hacen los calculos y no se que ha cambiado pero esta parte parece que no funciona

value_template: "{{ states('sensor.grid_import_export_power') | float | max(0) | round(0) }}"

si lo pruebas en la herramienta de desarrolladores (es una de mis capturas) ves que el float no parece gustarle

yo lo he  dejado value_template: "{{ states('sensor.grid_import_export_power') }}", eso si aun estoy revisando que los valores que devuelve sean correctos

saludos,

**Comment by homerj31** [comment]
> yo lo he arreglado asi y funciona: {{ [states('sensor.grid_import_export_power') | float, 0] | max(0) | round(1) }}

voy a probarlo como dices

**Comment by luuuis** [comment]
Ok, that is very strange that some sensors are reporting `9.223.372.036.854.776.000` as the value. I didn't notice this earlier when I looked on mobile at the images.

Could you [enable debug logging](https://github.com/luuuis/hass_wibeee/wiki/Troubleshooting#configure-logging) and then paste here the line that says `RAW Response from http://1.2.3.4/en/status.xml:` and then all the lines following that contain the XML response? I need this to determine if that value is something being returned from the device or something else.

The values should match the ones from the Wibeee device web UI.
![WiBeee 2022-02-09 16-28-40](https://user-images.githubusercontent.com/161006/153244959-6160449c-1fd6-4d80-90d8-e5f29cd91bd7.jpg)

**Comment by homerj31** [comment]
> @homerj31 @alexsalvo1 your problem with `|float` is surely a different issue than the one reported here. If you look at the screenshots you can see that the OP is directly using the `wibeee_<mac>_active_energy_l1` sensor of the integration and not the template sensors from the suggested configuration.
> 
> Can you please open a new issue and explain exactly what is happening in with the `grid_import_power` and `grid_export_power` **template** sensors for you? This would help me understand and update the documentation appropriately. It is very confusing to try to follow and troubleshoot 2 or 3 separate issues in one thread.

Mi problema en inicio es el mismo que el reportado al principio, en un momento dado, creo que pueda ser tras la actualización de ha a la versión [Release 2022.2.1 - February 3 no me refrescaba informacion el apartado de energia, y revisando las configuracion fue cuando vi en la herramienta de desarrolladores el error del float, mis disculpas si he podido crear confusion.

**Comment by macoca28021** [comment]
> Ok, es muy extraño que algunos sensores informen `9.223.372.036.854.776.000`como el valor. No me di cuenta de esto antes cuando miré las imágenes en el móvil.
> 
> ¿Podría [habilitar el registro de depuración](https://github.com/luuuis/hass_wibeee/wiki/Troubleshooting#configure-logging) y luego pegar aquí la línea que dice `RAW Response from http://1.2.3.4/en/status.xml:`y luego todas las líneas siguientes que contienen la respuesta XML? Necesito esto para determinar si ese valor es algo que se devuelve desde el dispositivo o algo más.
> 
> Los valores deben coincidir con los de la interfaz de usuario web del dispositivo Wibeee. ![WiBeee 2022-02-09 16-28-40](https://user-images.githubusercontent.com/161006/153244959-6160449c-1fd6-4d80-90d8-e5f29cd91bd7.jpg)

I am starting from 0. I just removed the integration and reinstalled it. I noticed that the active energy counters were exorbitant both L1 and L3 (L2 I do not use at the moment) and I went directly to the wibeee through the ip and verified that they had the same exorbitant values, so I have proceeded to reset ALL the values ​​so now I start from 0. I will inform you of the progress. I still don't understand him because of those values. I have been with another webeee integration for a long time and it had never happened to me, I removed it because I had to restart HA several times for it to detect the devices. Thank you and I will keep you informed.

This is how I have them now after the reset

![Screenshot_2](https://user-images.githubusercontent.com/82387245/153253972-9f7e5610-675a-47cc-86ed-c96277944795.png)

**Comment by luuuis** [comment]
Understood. If the device is reporting such an absurd value (it's actually `2^63 + 192`, whatever that means) there is not much that the integration can do about it, unfortunately.

This integration is reading the values from `status.xml` the same as the older one, only it is retrying failed requests to make things more reliable. The firmware running on the device is very buggy in my experience but this approach is working well for me and others, it's stable.

Out of curiosity, can you state what device and firmware version you are running? We have some compatibility info from user feedback in https://github.com/luuuis/hass_wibeee/wiki/Device-Compatibility.

**Comment by macoca28021** [comment]
> 
Device: Wibeee Box Mono
Firmware:  4.4.157
![image](https://user-images.githubusercontent.com/82387245/153283152-09f4e0bb-d18f-44ae-a9a8-a1982c2a54ab.png)

**Comment by macoca28021** [comment]
Finally!!!, Back to normal. Thank you all


![image](https://user-images.githubusercontent.com/82387245/153350753-5e954cd6-23d8-4f4e-8d51-43591b0687a9.png)

**Comment by macoca28021** [comment]
I continue with normal values.
But now I don't get the price
sorry to bother you so much

![Screenshot_70](https://user-images.githubusercontent.com/82387245/153390602-e109a35e-be95-44c4-80c2-f69e3594fd92.png)

![Screenshot_71](https://user-images.githubusercontent.com/82387245/153390723-748124df-6d8e-42e1-8206-fb9538b38d74.png)
