### ISSUE TITLE
Can’t create the sensor in the exemple code

### ISSUE THREAD

**Issue by lbarreiro** [luuuis/hass_wibeee#36]
I’m new to HA so forgive me to asking probably a noob question:

I replicate the exemple code to configuration.yaml file and check for errors. Also change the name of the sensor for the correct one.

it works with the sensor.grid_import_or_export_power, but the sensor.grid_import_power I have the “unavailable” and with sensor.grid_import_energy the result is unknown.

Do I miss a step?

**Comment by luuuis** [comment]
@lbarreiro I've had another report of problems in the example sensors but haven't had time to try it on different HA versions. Can you try the solution proposed in https://github.com/luuuis/hass_wibeee/issues/35#issuecomment-1033880699 and let me know?

**Comment by lbarreiro** [comment]
Obrigado Luis,

I just solve the issue by removing the `max(0)` and `min(0)` and create both independent and it works - beginners luck 
```
grid_imp_power:
        friendly_name: "Grid import"
        device_class: power
        unit_of_measurement: 'W'
        value_template: >-
            {% if states('sensor.wibeee_001ec03278d0_power_factor_l3') | float > 0 %}
              {{ states('sensor.wibeee_001ec03278d0_active_power_l3') | float * 1 | round(0) }}
            {% else %}
            {{ 0 }}
            {% endif %}
      grid_import_power:
        friendly_name: "Grid import power"
        device_class: power
        unit_of_measurement: 'W'
        value_template: "{{ states('sensor.grid_imp_power') | float | round(0) }}"
```

**Comment by luuuis** [comment]
This was due to a [breaking change introduced in 2022.2](https://community.home-assistant.io/t/sensor-not-working-after-update-to-2022-2/387940) regarding how the `max` filter works. Sensor examples have been updated and placed in the Wiki to make it easier to keep them in sync with HA.

https://github.com/luuuis/hass_wibeee/wiki/Sensor-Examples
