### ISSUE TITLE
sensor.wibeee_xxxxx_apparent_power_lx has unit VA which is unsupported for device_class power

### ISSUE THREAD

**Issue by IgnacioHR** [luuuis/hass_wibeee#42]
Hi,

I have plenty of messages like this in the log due to units that do not match the device_class. Also in the developer's menu, Statistics section there are messages related to some of the sensors coming from the WIBEE integration.

I recently visited the "integrations sensor" page:
https://www.home-assistant.io/integrations/sensor/
and notices there are "maybe new" device classes and units that might be more appropriate for some of the sensors, for example there is one device_class for "apparent_powe" whose unit it VA. and another one called "reactive_power" for a unit called "var" and another one for power_factor in the "%" unit.

So this issue is to send a heads up on this topic and see if it would be possible to update the sensor units.

Regards
Ignacio

**Comment by luuuis** [comment]
Thanks, I will look into it for the next release. If someone would like to submit a PR then the relevant code is the `KNOWN_SENSORS` table (the last two parameters are the unit and device class).

https://github.com/luuuis/hass_wibeee/blob/c9b6b5fe28b27a9939a19ef3095d7ae4966d57ad/custom_components/wibeee/sensor.py#L88-L100

As far as I know the warnings are harmless.

**Comment by luuuis** [comment]
These were added in https://github.com/home-assistant/core/pull/62010/

**Comment by IgnacioHR** [comment]
This morning I've created a PR for the 5 sensors that are the source of the warnings. The unit has been changed to var instead of original "VArL" and "VArC", I have been unable to find documentation on Internet about the "L" and "C" variants of the unit. I'm not an expert on this topic but I came to the conclusion that the surrounding real unit is "var" and the "L" and "C" are here to distinguish about the source so they should not be part of the unit itself

**Comment by luuuis** [comment]
Added in https://github.com/luuuis/hass_wibeee/pull/21 and released in [v3.2.1](https://github.com/luuuis/hass_wibeee/releases/tag/v3.2.1). Thank you for your contribution.
