### ISSUE TITLE
se pierde configuracion

### ISSUE THREAD

**Issue by homerj31** [luuuis/hass_wibeee#45]
buenas, con los reinicios de HA la configuracion se pierde y tengo que volver a meter los datos de la IP, ¿A alquien mas le pasa?

**Comment by luuuis** [comment]
Hello, I have not had any reports of lost configuration. Can you specify:
- what version of HA
- what version of Wibeee integration
- what type of configuration (YAML or UI)

**Comment by luuuis** [comment]
@homerj31 ?
