### ISSUE TITLE
Wibeee (old mirubee) local activation

### ISSUE THREAD

**Issue by carlosCastro99** [luuuis/hass_wibeee#48]
Hi Luis, this may not be a real issue, is more a doubt. In nest I can't find the option to change the IP in order to activate the local push. Can you help with that?

**Comment by luuuis** [comment]
No problem, @carlosCastro99. The Home Assistant IP address of needs to be entered in the device itself, not in Wibeee Nest. To open the device Web UI first locate the device in the HA device list (click link below).

[![My devices](https://my.home-assistant.io/badges/devices.svg)](https://my.home-assistant.io/redirect/devices/)

Once there, you can click "Visit Device" to go to the device Web UI (the default username and password are both `user`).

![](https://user-images.githubusercontent.com/161006/147990145-5e9e650a-ad92-4f9f-907c-d8c3f62fa74d.jpg)

Hope this helps.
