### ISSUE TITLE
Not showing active energy

### ISSUE THREAD

**Issue by Carapijo** [luuuis/hass_wibeee#50]
I´ve integrated Wibee into HA succesfully but when i try to insert it in the energy tab panel, the only 4 sensors shown are "Active energy" but their value is always "0".

I was trying to take data from "Capacitive Reactive Energy" (VARh) but they are not shown in the list to pick, linking to:
https://www.home-assistant.io/more-info/statistics/

Now i am doing this with Riemann sum integral and taking data from "Active power" sensor.

Is there any way to implement it directly?
Thanks.

**Comment by luuuis** [comment]
We are simply reporting what the device sends back as its energy consumption, @Carapijo. Can you check the device Web UI as described in https://github.com/luuuis/hass_wibeee/issues/48#issuecomment-1289121188 and take a screenshot? Or share the [debug level logs](https://github.com/luuuis/hass_wibeee/wiki/Troubleshooting).

**Comment by Carapijo** [comment]
> We are simply reporting what the device sends back as its energy consumption, @Carapijo. Can you check the device Web UI as described in [#48 (comment)](https://github.com/luuuis/hass_wibeee/issues/48#issuecomment-1289121188) and take a screenshot? Or share the [debug level logs](https://github.com/luuuis/hass_wibeee/wiki/Troubleshooting).

Sure, thank you

[img]https://tinypic.host/images/2022/10/30/Wibeee.jpg[/img]

**Comment by luuuis** [comment]
@Carapijo please go into the device UI itself, outside of home assistant. Then click "Phase 1" to see something like the following screenshot.
![WiBeee 2022-10-31 11-31-25](https://user-images.githubusercontent.com/161006/198998266-a37ad20f-3087-4c69-81d8-369664c27056.jpg)

What are the Active Energy values for phase 1/2/3?

**Comment by Carapijo** [comment]
@luuuis here is the screenshot of the probe
![Wibeee](https://user-images.githubusercontent.com/50950357/200088714-8838df34-16d8-4f57-b70b-e0e6e71d5139.jpg)

**Comment by luuuis** [comment]
It looks like the integration is working correctly and reporting the Active Energy from the device, @Carapijo. I don't know why that is reported as 0, if you contact Smilics support at the [Wibeee HelpDesk](https://smilics.atlassian.net/servicedesk/customer/portal/3) they may be able to help you with that.

As a workaround you can add an integration sensor to [calculate the energy usage inside Home Assistant](https://www.home-assistant.io/integrations/integration/#energy). There is an example in https://github.com/luuuis/hass_wibeee/wiki/Sensor-Examples#energy-sensors, just make sure that the `source` parameter is using the sensor for the clamp that you want to measure.

I will close this for now as the integration is working as expected.
