### ISSUE TITLE
Como usar medidor produção e consumo?

### ISSUE THREAD

**Issue by joaopedros2** [luuuis/hass_wibeee#55]
Bom dia! Peço desculpa de usar a língua portuguesa para o caso.
Eu tenho dois equipamentos wibeee. Trifásico e monofásico.
Utilizo o equipamento trifásico para medir o consumo energético da casa e o monofásico para medir a produção dos painéis.
O medidor está a captar dados pela linha 1 e injeta na fase 1 da rede de casa.
Os valores de medição de produção de energia não deveriam ser negativos?
Atualmente não consigo perceber o valor que estou a injetar agora a rede. Todos os valores se apresentam como positivos. Na app wibeee nest consigo mudar a orientação da linha e a produção aparece com valores negativos. O que devo fazer?

**Comment by luuuis** [comment]
Viva. O Wibeee não reporta os valores de energia e produção em separado por isso é necessário algum "pós-processamento". Tens exemplos de sensores de produção e consumo no Wiki, é só adaptar consoante a pinça que está em uso.

https://github.com/luuuis/hass_wibeee/wiki/Sensor-Examples#suggested-sensor-configurations

**Comment by joaopedros2** [comment]
Obrigado pela resposta e confesso que já tinha visto esse template.
Infelizmente não sei como aplicar no meu caso.
Será possível pedir-lhe ajuda na configuração?

**Comment by luuuis** [comment]
@joaopedros2 experimenta pesquisar por "como criar template sensor home assistant", existem vários resultados incluindo vídeos no YouTube. Isto da documentação oficial:  https://www.home-assistant.io/integrations/template/

Existe um fórum de língua portuguesa em https://forum.cpha.pt, pesquisa por lá também. Como não é uma questão específica desta integração vou dar esta questão como respondida.
