### ISSUE TITLE
Warning in log about invalid unit for `power_factor` device class

### ISSUE THREAD

**Issue by Abruzzi04** [luuuis/hass_wibeee#57]
`Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:677
Integration: Sensor (documentation, issues)
First occurred: 17:21:34 (2 occurrences)
Last logged: 17:21:34

Entity sensor.wibeee_84f3eba16954_power_factor_l1 (<class 'custom_components.wibeee.sensor.WibeeeSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('power_factor') it is using; expected one of ['%', 'no unit of measurement']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.wibeee_84f3eba16954_power_factor_l4 (<class 'custom_components.wibeee.sensor.WibeeeSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('power_factor') it is using; expected one of ['%', 'no unit of measurement']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.`

**Comment by luuuis** [comment]
Fixed in [v3.2.3](https://github.com/luuuis/hass_wibeee/releases/tag/v3.2.3).
