### ISSUE TITLE
Add configuration options to change the upstream URL

### ISSUE THREAD

**Issue by edurenye** [luuuis/hass_wibeee#61]
In https://github.com/luuuis/hass_wibeee/issues/59 you suggested me to use the [Local Push support](https://github.com/luuuis/hass_wibeee#configuring-local-push-optional-advanced), but I couldn't use it since my provider uses another upstream other than nest and they have their own app and so on. But I noticed that pulling all the time makes the wibeee device unresponsible from time to time and it doesn't happen when I stop pulling, so I want to try the 'Local Push support', as it should give no extra load to the device.

I think this is a great feature for all the people that does not use the official 'http://nest-ingest.wibeee.com' upstream.

**Comment by luuuis** [comment]
I agree with adding support for other providers. 

What is your provider, Iberdrola? Do you need to support arbitrary upstream URL or only a handful of ["known" destinations](https://github.com/fquinto/pywibeee/blob/b2f2f67e977d18d6ad2f6c7ccf12fc3321fa1c1b/emulator/wibeee_sender.py#L17-L21)?

![pywibeee 2023-04-15 22-20-16](https://user-images.githubusercontent.com/161006/232253575-e01749f3-cfe3-4a69-8a9c-37e0a46ed3e9.jpg)

I had a look at your PR, I will leave some comments shortly.

**Comment by luuuis** [comment]
@edurenye I temporarily forgot about this but now it's back on my radar, will be looking at it soon. Thanks for your patience.

**Comment by luuuis** [comment]
https://github.com/luuuis/hass_wibeee/releases/tag/v3.3.0-beta.0

**Comment by luuuis** [comment]
Finally released in [v3.3.0](https://github.com/luuuis/hass_wibeee/releases/tag/v3.3.0). Apologies for the delay.
