### ISSUE TITLE
Separating and integrating yields to jumps

### ISSUE THREAD

**Issue by antonio-fiol** [luuuis/hass_wibeee#64]
This is a comment on the suggestion to create a template sensor for import and another one for export. When integrating these, after a long time of being zero, the energy sensor shows a "jump" that isn't real.

It happens because it adds the area of a very wide triangle (all the time it was zero) and a small height (1W).

Any idea how to fix that?

![Screenshot_20230617_192930](https://github.com/luuuis/hass_wibeee/assets/23309681/4f966fd5-7b54-48a0-a6f6-7df885e38a86)

Otherwise, this integration seems to be working perfectly!! Thanks!!

**Comment by antonio-fiol** [comment]
I just added `method: left` to both grid_import_energy and grid_export_energy sensors, following advice from a thread showing a similar issue. I'll report success/failure here.

**Comment by luuuis** [comment]
Thanks for the report. I am assuming this is a reference to the example energy sensors in https://github.com/luuuis/hass_wibeee/wiki/Sensor-Examples#--energy-sensors.

Yes, I have `method: left` on all my integration sensors locally and that should probably be used included in the examples too. Let me know what you find.

**Comment by antonio-fiol** [comment]
`method: left` should indeed be in the examples :-)
