### ISSUE TITLE
port 8600

### ISSUE THREAD

**Issue by DIAZGZA** [luuuis/hass_wibeee#67]
It does not allow me the option nest proxy port 8600, port closed

**Comment by luuuis** [comment]
Hello, I don't understand this report. Please include: 
1. What version? 
1. Steps to reproduce
2. Expected behaviour
3. Actual behaviour

**Comment by DIAZGZA** [comment]
Ha

Core
2023.11.2
Supervisor
2023.11.3
Operating System
11.1
Frontend
20231030.2

Wibeee BOX
por Smilics
Firmware: 4.4.170

**Comment by luuuis** [comment]
Hello, I'm not able to help if you don't describe exactly what is happening. Do you have error logs or a screenshot? Or just:
- Steps to reproduce
- Expected behaviour
- Actual behaviour
