### ISSUE TITLE
HA Modbus integration 

### ISSUE THREAD

**Issue by alexsalvo1** [luuuis/hass_wibeee#76]
Hi, Are you planning a Modbus version of this integration? it seems that now when you enable Modbus it continue to send data to the cloud platform (Nest)

**Comment by luuuis** [comment]
Closed due to no reply.

**Comment by alexsalvo1** [comment]
Sorry for the late answer.

The problem is that with latest version of wibeee box 4.4.171, using the pooling only configuration the wibeee at one point dtop to send ingo to the cloud. I started from 15s of refresh and now i'm at 90s, but it just reduce the posibility it stop.

**Comment by luuuis** [comment]
Wibeee devices are known to become unstable when using polling APIs. Having said that, there have been no reports of instability in the Nest push side of things, nor have I experienced this. This is the first such report.

The solution for instability is to [configure Local Push](https://github.com/luuuis/hass_wibeee/?tab=readme-ov-file#configuring-local-push-optional-advanced) and then set the polling interval to a much higher value (minutes).

High polling interval with Local Push will keep the Wibeee stable while you still receive high frequency updates (same frequency that is sent to  Wibeee Nest). In my installation I have polling configured for every 30 minutes and sensors still update every few seconds through Local Push.

<img src="https://github.com/luuuis/hass_wibeee/assets/161006/bc7635c4-7669-44cb-b377-2a797c3e3e60" width="300" /> 
<img src="https://github.com/luuuis/hass_wibeee/assets/161006/8f4e6f9d-e70f-49bb-87f1-5f07acdef891" width="400" />

Please note I am considering making this kind of setup mandatory in future versions (poll interval every 1 minute and not configurable).

It doesn't make sense to implement a new protocol when the solution already exists. Also, there is no guarantee that Modbus support would be more stable.

@alexsalvo1 out of curiosity where have you seen that Nest upload continues to work when using Modbus?
