### ISSUE TITLE
Wibeee Sensors not showing in HASS (fw 4.6.170)

### ISSUE THREAD

**Issue by ptoharia** [luuuis/hass_wibeee#81]
My Wibeee is a Wibeee BOX with fw version 4.6.170 and I get this error in HASS: 

`Error getting http://192.168.1.199/services/user/values2.xml?id=WIBEEE after 10 retries: ServerDisconnectedError: Server disconnected`

I have checked via command line that this URL returns an error but if I change values2.xml to values.xml it does work. And it also works  http://192.168.1.199/en/status.xml

But I have not been able to configure the integration to use one of these URLs. Can you help me with this? 

Thanks!

**Comment by luuuis** [comment]
Hi @ptoharia ,

It seems the `values2.xml` API discussed in #68 is not available any more. Strange that `status.xml` is back, not sure what  Wibeee is up to.

To fix this I will have to release a new version using perhaps `values.xml` as that is a publicly-documented API. In the meantime please downgrade to https://github.com/luuuis/hass_wibeee/releases/tag/v3.3.0 for the time being and it should work for you–please confirm if that's the case.

**Comment by ptoharia** [comment]
Yes! Great, that worked. Thanks for your help and your work on this component. Btw, the values2.xml does not work but the values.xml does, no idea if they are compatible.

**Comment by luuuis** [comment]
@ptoharia do try https://github.com/luuuis/hass_wibeee/releases/tag/v3.5.0-beta.0 when you get a chance. That version is using `values.xml` which is available all firmware versions as far as I know.

**Comment by ptoharia** [comment]
That beta seems to work perfectly! Thanks! El 14 feb 2024, a las 0:15, Luis Miranda ***@***.***> escribió:﻿
@ptoharia do try https://github.com/luuuis/hass_wibeee/releases/tag/v3.5.0-beta.0 when you get a chance. That version is using values.xml which is available all firmware versions as far as I know.

**Comment by luuuis** [comment]
https://github.com/luuuis/hass_wibeee/releases/tag/v3.5.0
