### ISSUE TITLE
Issues using tthe Wibeee Nest option

### ISSUE THREAD

**Issue by povinhox** [luuuis/hass_wibeee#87]
Hi luuuis,

I've tried to configure the Wibee HACS integration using the Wibeee Nest option, but it seems that I'm having some issues.
Note: I'm trying this option since I'm trying to move from the XML pooling each minute, since my Wibee started auto reset it self during the day.

Wibee BOX Mono: Firmware 4.4.171
HomeAssistant: Core 2024.2.2 
Wibee HACS: 3.5.0

Steps to reproduce
1. Configured the WibeeBox with server: 192.168.1.89, Port 8600
2. Configured HA integration with Wibeee Nest option; Device Polling Interval: 1200

Expected behavior
1. The Wibee box should have the blue light fixed and the red light blinking normally
2. In the HA the data should update each second
3. The NEST App should be updated each second

Actual behavior
1. The Wibee box has the blue light blinking fast and the red light blinking normally 
2. In the HA the data updates randomly, normally each 10 to 60 seconds
3. The NEST App updated at the beginning then stopped updating

What extra information or action do you need me to provide?

Thank you

**Comment by luuuis** [comment]
Please enable debug logging, restart the integration and let it collect logs for a while. Then include here or send to cheery.key9586@fastmail.com.

https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging

**Comment by povinhox** [comment]
I've have to correct something. Actually looking now to the graphs on HA, the HA is being updated each 5 seconds. So there is not issue there. It's just weird that the Wibee Box light display like it cannot find the server. 
The major issue seems to be the lack, or sporadic, Nest updates. I've also restart the HA server just to be sure it was not something that was hanging the HA.

The Energy Power graphics:
<img width="377" alt="HA-Wibee-HACS-Power" src="https://github.com/luuuis/hass_wibeee/assets/77890693/a7cdec8e-ab96-481d-8ad3-21d7b4d0ebd5">
<img width="369" alt="NEST-Wibee-Power" src="https://github.com/luuuis/hass_wibeee/assets/77890693/f7ea453a-fa5f-41ab-8f0f-10ae7e5cf842">

I'm also adding a screenshot of the  configuration:
<img width="268" alt="Captura de ecrã 2024-02-23 121007" src="https://github.com/luuuis/hass_wibeee/assets/77890693/52e75ed2-f295-422f-92ab-fb84fb49859a">

As for the debug log you requested, surprisingly they do not show much, is all about the warnings related to HACS integrations, nothing more. Here is the line about Wibeee integrations, there is nothing about inbound or outbound communications:

 `2024-02-23 12:56:42.004 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration wibeee which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

I remember that the last time I came to you with an issues, that was related to the new Firware version not pulling the XLM file the logs were very detailed. Not sure if his has to do with HA new version or there is any extra hidden option I need to turn on.

Thank you,

**Comment by luuuis** [comment]
Did you [enable debug logging](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging)?

**Comment by povinhox** [comment]
Yes! I did. And just did it again. But only reports what is already in the HA Core Log:
<img width="715" alt="Captura de ecrã 2024-02-23 151115" src="https://github.com/luuuis/hass_wibeee/assets/77890693/868ac0d5-d0f8-4f3b-a5b5-089c82708faa">
It pops up this file once I turn it off: : 
[home-assistant_wibeee_2024-02-23T15-18-09.715Z.log](https://github.com/luuuis/hass_wibeee/files/14386861/home-assistant_wibeee_2024-02-23T15-18-09.715Z.log)
I've reloaded the integration and waited some minutes.
The HA Core Log shows the same content:
<img width="770" alt="HA-Core-Log" src="https://github.com/luuuis/hass_wibeee/assets/77890693/f1801a08-1058-49b8-af01-d33963fe792a">
Has I said before. It's strange, since when I raised another issue with you before, It was showing more data.

**Comment by luuuis** [comment]
> Then after a while the historical graph gets the correct information. It's that normal behavior?

I would not say it is normal but it's not wrong either. Here are the various paths that Wibeee uses to send information.

https://github.com/luuuis/hass_wibeee/blob/11c8f15928b395d0d29e425b87987bad25000d71/custom_components/wibeee/nest.py#L101-L105

I will not claim to understand the exact difference between all of them but some send a single measure (for "now") and others send multiple measures corresponding to a time span. For example, if your internet is broken for a time then Wibeee will save measurements to local memory and send them to Wibeee Cloud later. When the internet is back Wibeee may send information for a 1 hour time span.  In the integration we are only saving the single measurements and we send the rest to Wibeee Cloud.

Unfortunately, without logs it will be difficult to investigate this issue any further.
