### ISSUE TITLE
Iberdrola changed URL of Wibeee server data: ingest-prod-iberdrola.wibeee.com

### ISSUE THREAD

**Issue by feserdel** [luuuis/hass_wibeee#90]
10 days ago my Wibeee stopped working. Errors show timeouts when getting Wibeee data. After trying several options, I found that factory resetting the device and joining again using Iberdrola's Monitor Smart app, now is back to work.

However, URL of Iberdrola Server has changed. Now the device has the following config: <img width="356" alt="image" src="https://github.com/luuuis/hass_wibeee/assets/118628912/956d11c7-4622-49cf-8d38-2b8b0ec671bd">

May be necessary to change hass_wibee integration to reflect this new server, or allow manually enter URL of server for relaying data.

**Comment by luuuis** [comment]
Thanks. I think it should continue to work because the old name is an alias for `ingest-prod-iberdrola.wibeee.com`. Can you confirm?

![luis — -zsh — ⌥⌘1 2024-02-27 20-22-05](https://github.com/luuuis/hass_wibeee/assets/161006/d9b6f528-8353-4589-8632-aad9cf6158b6)

I will update it in the next release.

**Comment by feserdel** [comment]
When I configure hass_wibee integration in "local only (no cloud)", everything works as expected: no errors, sensors woking. 

However, if I configure in mode "Coud (Iberdrola)", the integration fail to start. And I get the following error:

 ```
2024-02-28 07:35:51.842 ERROR (MainThread) [custom_components.wibeee.api] **Error getting http://192.168.***.***/services/user/devices.xml after 5 retries: TimeoutError:** 
2024-02-28 07:35:51.843 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/wibeee/sensor.py", line 217, in async_setup_entry
    device = await api.async_fetch_device_info(retries=5)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wibeee/api.py", line 66, in async_fetch_device_info
    device_id = devices['devices']['id']
                ~~~~~~~^^^^^^^^^^^
```

I habe seen this error before, from about 10 days ago. May be this error has another origin?.

NOTE: In "Local only" mode, the answer from  /services/user/devices.xml of wibeee device is:
```
 <devices>
<id>WIBEEE</id>
</devices>
```

However, in "Iberdrola cloud" mode, same URL resturns strange string:

```
AT+CIPSENDBUF=4,807
31a
{"time":"1709072026","v1":"232.71","v2":"232.71","v3":"232.71","vt":"232.00","i1":"0.00","i2":"0.41","i3":"1.24","it":"1.65","p1":"0","p2":"96
```
In each case, after changing the integration mode, I restart Home Assistant.

**Comment by luuuis** [comment]
The fact that it worked or didn't is likely a coincidence as there should be no difference between Local-only and the Cloud modes as far as the device is concerned. The only difference is whether HA sends the data to the Wibeee Cloud. Please send debug logs if this persists.

Regarding the errors in your log, the Wibeee device APIs are unreliable. Sometimes they will returns a proper response and at other times they return garbage like in your example above. If you 

Note: there is no need to restart Home Assistant, nor does it make any difference except to add more wait time before retrying. Normally it is enough to reload the integration.

**Comment by feserdel** [comment]
Good morning. I did the following:

- Enable debugging
- Change Cloud mode to iberdrola
      - integration seems to be working correctly
- Restart home assistant
      - Integration still works ccorrectly
- disable debugging

As for now, everything seems to be working correctly. So you can close this issue

Thank you for your suppport!!
